spring:
  #RabbitMQ Configuration
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost} # Default to localhost if not set
    port: ${SPRING_RABBITMQ_PORT:5672}      # Default to 5672 if not set
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
